apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Never
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - name: nginx-logs-storage
            mountPath: /var/log/nginx
      volumes:
        - name: nginx-logs-storage
          persistentVolumeClaim:
            claimName: local-pv
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  ports:
  - nodePort: 30880
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: NodePort

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pv
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10m
